-- 코드를 입력하세요
# SELECT TITLE, BOARD_ID, REPLY_ID, WRITER_ID, CONTENTS, CREATED_DATE 
# FROM USED_GOODS_BOARD, USED_GOODS_REPLY
# WHERE CREATED_DATE = 2022-10
# ORDER BY CREATED_DATE ASC, TITLE ASC;

# SELECT 
#     b.TITLE,
#     b.BOARD_ID,
#     r.REPLY_ID,
#     r.WRITER_ID,
#     r.CONTENTS,
#     DATE_FORMAT(r.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
# FROM USED_GOODS_BOARD b, USED_GOODS_REPLY r
# WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
# ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;

SELECT 
    b.TITLE,
    b.BOARD_ID,
    r.REPLY_ID,
    r.WRITER_ID,
    r.CONTENTS,
    DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD b
JOIN USED_GOODS_REPLY r ON b.BOARD_ID = r.BOARD_ID
WHERE DATE_FORMAT(b.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY r.CREATED_DATE ASC, b.TITLE ASC;
